/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteRouteImport } from './routes/project/route'
import { Route as CommitteeRouteRouteImport } from './routes/committee/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as PushNotificationIndexRouteImport } from './routes/pushNotification/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as ForbiddenIndexRouteImport } from './routes/forbidden/index'
import { Route as CommitteeIndexRouteImport } from './routes/committee/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DevUiComponentsIndexRouteImport } from './routes/dev/ui/components/index'
import { Route as AuthRegisterVerifyIndexRouteImport } from './routes/auth/register/verify/index'
import { Route as AuthRegisterSetupIndexRouteImport } from './routes/auth/register/setup/index'

const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRouteRoute = CommitteeRouteRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const PushNotificationIndexRoute = PushNotificationIndexRouteImport.update({
  id: '/pushNotification/',
  path: '/pushNotification/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ForbiddenIndexRoute = ForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeIndexRoute = CommitteeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DevUiComponentsIndexRoute = DevUiComponentsIndexRouteImport.update({
  id: '/dev/ui/components/',
  path: '/dev/ui/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterVerifyIndexRoute = AuthRegisterVerifyIndexRouteImport.update({
  id: '/register/verify/',
  path: '/register/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterSetupIndexRoute = AuthRegisterSetupIndexRouteImport.update({
  id: '/register/setup/',
  path: '/register/setup/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/committee': typeof CommitteeRouteRouteWithChildren
  '/project': typeof ProjectRouteRouteWithChildren
  '/committee/': typeof CommitteeIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/pushNotification/': typeof PushNotificationIndexRoute
  '/search/': typeof SearchIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup/': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify/': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components/': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/committee': typeof CommitteeIndexRoute
  '/forbidden': typeof ForbiddenIndexRoute
  '/project': typeof ProjectIndexRoute
  '/pushNotification': typeof PushNotificationIndexRoute
  '/search': typeof SearchIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/committee': typeof CommitteeRouteRouteWithChildren
  '/project': typeof ProjectRouteRouteWithChildren
  '/committee/': typeof CommitteeIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/pushNotification/': typeof PushNotificationIndexRoute
  '/search/': typeof SearchIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup/': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify/': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components/': typeof DevUiComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/committee'
    | '/project'
    | '/committee/'
    | '/forbidden/'
    | '/project/'
    | '/pushNotification/'
    | '/search/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/auth/register/setup/'
    | '/auth/register/verify/'
    | '/dev/ui/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/committee'
    | '/forbidden'
    | '/project'
    | '/pushNotification'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/register/setup'
    | '/auth/register/verify'
    | '/dev/ui/components'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/committee'
    | '/project'
    | '/committee/'
    | '/forbidden/'
    | '/project/'
    | '/pushNotification/'
    | '/search/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/auth/register/setup/'
    | '/auth/register/verify/'
    | '/dev/ui/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CommitteeRouteRoute: typeof CommitteeRouteRouteWithChildren
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  ForbiddenIndexRoute: typeof ForbiddenIndexRoute
  PushNotificationIndexRoute: typeof PushNotificationIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  DevUiComponentsIndexRoute: typeof DevUiComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pushNotification/': {
      id: '/pushNotification/'
      path: '/pushNotification'
      fullPath: '/pushNotification/'
      preLoaderRoute: typeof PushNotificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/forbidden/': {
      id: '/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee/': {
      id: '/committee/'
      path: '/'
      fullPath: '/committee/'
      preLoaderRoute: typeof CommitteeIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dev/ui/components/': {
      id: '/dev/ui/components/'
      path: '/dev/ui/components'
      fullPath: '/dev/ui/components/'
      preLoaderRoute: typeof DevUiComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/verify/': {
      id: '/auth/register/verify/'
      path: '/register/verify'
      fullPath: '/auth/register/verify/'
      preLoaderRoute: typeof AuthRegisterVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/setup/': {
      id: '/auth/register/setup/'
      path: '/register/setup'
      fullPath: '/auth/register/setup/'
      preLoaderRoute: typeof AuthRegisterSetupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthRegisterSetupIndexRoute: typeof AuthRegisterSetupIndexRoute
  AuthRegisterVerifyIndexRoute: typeof AuthRegisterVerifyIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthRegisterSetupIndexRoute: AuthRegisterSetupIndexRoute,
  AuthRegisterVerifyIndexRoute: AuthRegisterVerifyIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CommitteeRouteRouteChildren {
  CommitteeIndexRoute: typeof CommitteeIndexRoute
}

const CommitteeRouteRouteChildren: CommitteeRouteRouteChildren = {
  CommitteeIndexRoute: CommitteeIndexRoute,
}

const CommitteeRouteRouteWithChildren = CommitteeRouteRoute._addFileChildren(
  CommitteeRouteRouteChildren,
)

interface ProjectRouteRouteChildren {
  ProjectIndexRoute: typeof ProjectIndexRoute
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectIndexRoute: ProjectIndexRoute,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CommitteeRouteRoute: CommitteeRouteRouteWithChildren,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  ForbiddenIndexRoute: ForbiddenIndexRoute,
  PushNotificationIndexRoute: PushNotificationIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  DevUiComponentsIndexRoute: DevUiComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
