/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as PushNotificationIndexRouteImport } from './routes/pushNotification/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DevUiComponentsIndexRouteImport } from './routes/dev/ui/components/index'
import { Route as AuthRegisterVerifyIndexRouteImport } from './routes/auth/register/verify/index'
import { Route as AuthRegisterSetupIndexRouteImport } from './routes/auth/register/setup/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const PushNotificationIndexRoute = PushNotificationIndexRouteImport.update({
  id: '/pushNotification/',
  path: '/pushNotification/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/auth/reset-password/',
  path: '/auth/reset-password/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiComponentsIndexRoute = DevUiComponentsIndexRouteImport.update({
  id: '/dev/ui/components/',
  path: '/dev/ui/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterVerifyIndexRoute = AuthRegisterVerifyIndexRouteImport.update({
  id: '/auth/register/verify/',
  path: '/auth/register/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterSetupIndexRoute = AuthRegisterSetupIndexRouteImport.update({
  id: '/auth/register/setup/',
  path: '/auth/register/setup/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pushNotification/': typeof PushNotificationIndexRoute
  '/search/': typeof SearchIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup/': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify/': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components/': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pushNotification': typeof PushNotificationIndexRoute
  '/search': typeof SearchIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pushNotification/': typeof PushNotificationIndexRoute
  '/search/': typeof SearchIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/register/setup/': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify/': typeof AuthRegisterVerifyIndexRoute
  '/dev/ui/components/': typeof DevUiComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pushNotification/'
    | '/search/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/auth/register/setup/'
    | '/auth/register/verify/'
    | '/dev/ui/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pushNotification'
    | '/search'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/auth/register/setup'
    | '/auth/register/verify'
    | '/dev/ui/components'
  id:
    | '__root__'
    | '/'
    | '/pushNotification/'
    | '/search/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/auth/register/setup/'
    | '/auth/register/verify/'
    | '/dev/ui/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PushNotificationIndexRoute: typeof PushNotificationIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthRegisterSetupIndexRoute: typeof AuthRegisterSetupIndexRoute
  AuthRegisterVerifyIndexRoute: typeof AuthRegisterVerifyIndexRoute
  DevUiComponentsIndexRoute: typeof DevUiComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pushNotification/': {
      id: '/pushNotification/'
      path: '/pushNotification'
      fullPath: '/pushNotification/'
      preLoaderRoute: typeof PushNotificationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui/components/': {
      id: '/dev/ui/components/'
      path: '/dev/ui/components'
      fullPath: '/dev/ui/components/'
      preLoaderRoute: typeof DevUiComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/verify/': {
      id: '/auth/register/verify/'
      path: '/auth/register/verify'
      fullPath: '/auth/register/verify/'
      preLoaderRoute: typeof AuthRegisterVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/setup/': {
      id: '/auth/register/setup/'
      path: '/auth/register/setup'
      fullPath: '/auth/register/setup/'
      preLoaderRoute: typeof AuthRegisterSetupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PushNotificationIndexRoute: PushNotificationIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthRegisterSetupIndexRoute: AuthRegisterSetupIndexRoute,
  AuthRegisterVerifyIndexRoute: AuthRegisterVerifyIndexRoute,
  DevUiComponentsIndexRoute: DevUiComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
