/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteRouteImport } from './routes/project/route'
import { Route as DocsRouteRouteImport } from './routes/docs/route'
import { Route as DevRouteRouteImport } from './routes/dev/route'
import { Route as CommitteeRouteRouteImport } from './routes/committee/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectIndexRouteImport } from './routes/project/index'
import { Route as ForbiddenIndexRouteImport } from './routes/forbidden/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as CommitteeIndexRouteImport } from './routes/committee/index'
import { Route as DocsSlugRouteImport } from './routes/docs/$slug'
import { Route as ProjectNoticeIndexRouteImport } from './routes/project/notice/index'
import { Route as ProjectMembersIndexRouteImport } from './routes/project/members/index'
import { Route as ProjectFormsIndexRouteImport } from './routes/project/forms/index'
import { Route as DevTableIndexRouteImport } from './routes/dev/table/index'
import { Route as DevSearchIndexRouteImport } from './routes/dev/search/index'
import { Route as DevPushNotificationIndexRouteImport } from './routes/dev/pushNotification/index'
import { Route as DevCommitteeMemberIndexRouteImport } from './routes/dev/committeeMember/index'
import { Route as CommitteeNoticeIndexRouteImport } from './routes/committee/notice/index'
import { Route as CommitteeMembersIndexRouteImport } from './routes/committee/members/index'
import { Route as CommitteeFormsIndexRouteImport } from './routes/committee/forms/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as DevUiComponentsIndexRouteImport } from './routes/dev/ui/components/index'
import { Route as CommitteeNoticeNoticeIdIndexRouteImport } from './routes/committee/notice/$noticeId/index'
import { Route as AuthRegisterVerifyIndexRouteImport } from './routes/auth/register/verify/index'
import { Route as AuthRegisterSetupIndexRouteImport } from './routes/auth/register/setup/index'

const ProjectRouteRoute = ProjectRouteRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRouteRoute = DocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DevRouteRoute = DevRouteRouteImport.update({
  id: '/dev',
  path: '/dev',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRouteRoute = CommitteeRouteRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ForbiddenIndexRoute = ForbiddenIndexRouteImport.update({
  id: '/forbidden/',
  path: '/forbidden/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocsRouteRoute,
} as any)
const CommitteeIndexRoute = CommitteeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const DocsSlugRoute = DocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => DocsRouteRoute,
} as any)
const ProjectNoticeIndexRoute = ProjectNoticeIndexRouteImport.update({
  id: '/notice/',
  path: '/notice/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectMembersIndexRoute = ProjectMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const ProjectFormsIndexRoute = ProjectFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => ProjectRouteRoute,
} as any)
const DevTableIndexRoute = DevTableIndexRouteImport.update({
  id: '/table/',
  path: '/table/',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevSearchIndexRoute = DevSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => DevRouteRoute,
} as any)
const DevPushNotificationIndexRoute =
  DevPushNotificationIndexRouteImport.update({
    id: '/pushNotification/',
    path: '/pushNotification/',
    getParentRoute: () => DevRouteRoute,
  } as any)
const DevCommitteeMemberIndexRoute = DevCommitteeMemberIndexRouteImport.update({
  id: '/committeeMember/',
  path: '/committeeMember/',
  getParentRoute: () => DevRouteRoute,
} as any)
const CommitteeNoticeIndexRoute = CommitteeNoticeIndexRouteImport.update({
  id: '/notice/',
  path: '/notice/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const CommitteeMembersIndexRoute = CommitteeMembersIndexRouteImport.update({
  id: '/members/',
  path: '/members/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const CommitteeFormsIndexRoute = CommitteeFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => CommitteeRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DevUiComponentsIndexRoute = DevUiComponentsIndexRouteImport.update({
  id: '/ui/components/',
  path: '/ui/components/',
  getParentRoute: () => DevRouteRoute,
} as any)
const CommitteeNoticeNoticeIdIndexRoute =
  CommitteeNoticeNoticeIdIndexRouteImport.update({
    id: '/notice/$noticeId/',
    path: '/notice/$noticeId/',
    getParentRoute: () => CommitteeRouteRoute,
  } as any)
const AuthRegisterVerifyIndexRoute = AuthRegisterVerifyIndexRouteImport.update({
  id: '/register/verify/',
  path: '/register/verify/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterSetupIndexRoute = AuthRegisterSetupIndexRouteImport.update({
  id: '/register/setup/',
  path: '/register/setup/',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/committee': typeof CommitteeRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/project': typeof ProjectRouteRouteWithChildren
  '/docs/$slug': typeof DocsSlugRoute
  '/committee/': typeof CommitteeIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/committee/forms/': typeof CommitteeFormsIndexRoute
  '/committee/members/': typeof CommitteeMembersIndexRoute
  '/committee/notice/': typeof CommitteeNoticeIndexRoute
  '/dev/committeeMember/': typeof DevCommitteeMemberIndexRoute
  '/dev/pushNotification/': typeof DevPushNotificationIndexRoute
  '/dev/search/': typeof DevSearchIndexRoute
  '/dev/table/': typeof DevTableIndexRoute
  '/project/forms/': typeof ProjectFormsIndexRoute
  '/project/members/': typeof ProjectMembersIndexRoute
  '/project/notice/': typeof ProjectNoticeIndexRoute
  '/auth/register/setup/': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify/': typeof AuthRegisterVerifyIndexRoute
  '/committee/notice/$noticeId/': typeof CommitteeNoticeNoticeIdIndexRoute
  '/dev/ui/components/': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/docs/$slug': typeof DocsSlugRoute
  '/committee': typeof CommitteeIndexRoute
  '/docs': typeof DocsIndexRoute
  '/forbidden': typeof ForbiddenIndexRoute
  '/project': typeof ProjectIndexRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/committee/forms': typeof CommitteeFormsIndexRoute
  '/committee/members': typeof CommitteeMembersIndexRoute
  '/committee/notice': typeof CommitteeNoticeIndexRoute
  '/dev/committeeMember': typeof DevCommitteeMemberIndexRoute
  '/dev/pushNotification': typeof DevPushNotificationIndexRoute
  '/dev/search': typeof DevSearchIndexRoute
  '/dev/table': typeof DevTableIndexRoute
  '/project/forms': typeof ProjectFormsIndexRoute
  '/project/members': typeof ProjectMembersIndexRoute
  '/project/notice': typeof ProjectNoticeIndexRoute
  '/auth/register/setup': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify': typeof AuthRegisterVerifyIndexRoute
  '/committee/notice/$noticeId': typeof CommitteeNoticeNoticeIdIndexRoute
  '/dev/ui/components': typeof DevUiComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/committee': typeof CommitteeRouteRouteWithChildren
  '/dev': typeof DevRouteRouteWithChildren
  '/docs': typeof DocsRouteRouteWithChildren
  '/project': typeof ProjectRouteRouteWithChildren
  '/docs/$slug': typeof DocsSlugRoute
  '/committee/': typeof CommitteeIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/forbidden/': typeof ForbiddenIndexRoute
  '/project/': typeof ProjectIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/committee/forms/': typeof CommitteeFormsIndexRoute
  '/committee/members/': typeof CommitteeMembersIndexRoute
  '/committee/notice/': typeof CommitteeNoticeIndexRoute
  '/dev/committeeMember/': typeof DevCommitteeMemberIndexRoute
  '/dev/pushNotification/': typeof DevPushNotificationIndexRoute
  '/dev/search/': typeof DevSearchIndexRoute
  '/dev/table/': typeof DevTableIndexRoute
  '/project/forms/': typeof ProjectFormsIndexRoute
  '/project/members/': typeof ProjectMembersIndexRoute
  '/project/notice/': typeof ProjectNoticeIndexRoute
  '/auth/register/setup/': typeof AuthRegisterSetupIndexRoute
  '/auth/register/verify/': typeof AuthRegisterVerifyIndexRoute
  '/committee/notice/$noticeId/': typeof CommitteeNoticeNoticeIdIndexRoute
  '/dev/ui/components/': typeof DevUiComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/committee'
    | '/dev'
    | '/docs'
    | '/project'
    | '/docs/$slug'
    | '/committee/'
    | '/docs/'
    | '/forbidden/'
    | '/project/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/committee/forms/'
    | '/committee/members/'
    | '/committee/notice/'
    | '/dev/committeeMember/'
    | '/dev/pushNotification/'
    | '/dev/search/'
    | '/dev/table/'
    | '/project/forms/'
    | '/project/members/'
    | '/project/notice/'
    | '/auth/register/setup/'
    | '/auth/register/verify/'
    | '/committee/notice/$noticeId/'
    | '/dev/ui/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dev'
    | '/docs/$slug'
    | '/committee'
    | '/docs'
    | '/forbidden'
    | '/project'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/committee/forms'
    | '/committee/members'
    | '/committee/notice'
    | '/dev/committeeMember'
    | '/dev/pushNotification'
    | '/dev/search'
    | '/dev/table'
    | '/project/forms'
    | '/project/members'
    | '/project/notice'
    | '/auth/register/setup'
    | '/auth/register/verify'
    | '/committee/notice/$noticeId'
    | '/dev/ui/components'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/committee'
    | '/dev'
    | '/docs'
    | '/project'
    | '/docs/$slug'
    | '/committee/'
    | '/docs/'
    | '/forbidden/'
    | '/project/'
    | '/auth/login/'
    | '/auth/register/'
    | '/auth/reset-password/'
    | '/committee/forms/'
    | '/committee/members/'
    | '/committee/notice/'
    | '/dev/committeeMember/'
    | '/dev/pushNotification/'
    | '/dev/search/'
    | '/dev/table/'
    | '/project/forms/'
    | '/project/members/'
    | '/project/notice/'
    | '/auth/register/setup/'
    | '/auth/register/verify/'
    | '/committee/notice/$noticeId/'
    | '/dev/ui/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  CommitteeRouteRoute: typeof CommitteeRouteRouteWithChildren
  DevRouteRoute: typeof DevRouteRouteWithChildren
  DocsRouteRoute: typeof DocsRouteRouteWithChildren
  ProjectRouteRoute: typeof ProjectRouteRouteWithChildren
  ForbiddenIndexRoute: typeof ForbiddenIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev': {
      id: '/dev'
      path: '/dev'
      fullPath: '/dev'
      preLoaderRoute: typeof DevRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/': {
      id: '/project/'
      path: '/'
      fullPath: '/project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/forbidden/': {
      id: '/forbidden/'
      path: '/forbidden'
      fullPath: '/forbidden/'
      preLoaderRoute: typeof ForbiddenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/committee/': {
      id: '/committee/'
      path: '/'
      fullPath: '/committee/'
      preLoaderRoute: typeof CommitteeIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/docs/$slug': {
      id: '/docs/$slug'
      path: '/$slug'
      fullPath: '/docs/$slug'
      preLoaderRoute: typeof DocsSlugRouteImport
      parentRoute: typeof DocsRouteRoute
    }
    '/project/notice/': {
      id: '/project/notice/'
      path: '/notice'
      fullPath: '/project/notice/'
      preLoaderRoute: typeof ProjectNoticeIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/members/': {
      id: '/project/members/'
      path: '/members'
      fullPath: '/project/members/'
      preLoaderRoute: typeof ProjectMembersIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/project/forms/': {
      id: '/project/forms/'
      path: '/forms'
      fullPath: '/project/forms/'
      preLoaderRoute: typeof ProjectFormsIndexRouteImport
      parentRoute: typeof ProjectRouteRoute
    }
    '/dev/table/': {
      id: '/dev/table/'
      path: '/table'
      fullPath: '/dev/table/'
      preLoaderRoute: typeof DevTableIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/search/': {
      id: '/dev/search/'
      path: '/search'
      fullPath: '/dev/search/'
      preLoaderRoute: typeof DevSearchIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/pushNotification/': {
      id: '/dev/pushNotification/'
      path: '/pushNotification'
      fullPath: '/dev/pushNotification/'
      preLoaderRoute: typeof DevPushNotificationIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/dev/committeeMember/': {
      id: '/dev/committeeMember/'
      path: '/committeeMember'
      fullPath: '/dev/committeeMember/'
      preLoaderRoute: typeof DevCommitteeMemberIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/committee/notice/': {
      id: '/committee/notice/'
      path: '/notice'
      fullPath: '/committee/notice/'
      preLoaderRoute: typeof CommitteeNoticeIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/committee/members/': {
      id: '/committee/members/'
      path: '/members'
      fullPath: '/committee/members/'
      preLoaderRoute: typeof CommitteeMembersIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/committee/forms/': {
      id: '/committee/forms/'
      path: '/forms'
      fullPath: '/committee/forms/'
      preLoaderRoute: typeof CommitteeFormsIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dev/ui/components/': {
      id: '/dev/ui/components/'
      path: '/ui/components'
      fullPath: '/dev/ui/components/'
      preLoaderRoute: typeof DevUiComponentsIndexRouteImport
      parentRoute: typeof DevRouteRoute
    }
    '/committee/notice/$noticeId/': {
      id: '/committee/notice/$noticeId/'
      path: '/notice/$noticeId'
      fullPath: '/committee/notice/$noticeId/'
      preLoaderRoute: typeof CommitteeNoticeNoticeIdIndexRouteImport
      parentRoute: typeof CommitteeRouteRoute
    }
    '/auth/register/verify/': {
      id: '/auth/register/verify/'
      path: '/register/verify'
      fullPath: '/auth/register/verify/'
      preLoaderRoute: typeof AuthRegisterVerifyIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/register/setup/': {
      id: '/auth/register/setup/'
      path: '/register/setup'
      fullPath: '/auth/register/setup/'
      preLoaderRoute: typeof AuthRegisterSetupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthRegisterSetupIndexRoute: typeof AuthRegisterSetupIndexRoute
  AuthRegisterVerifyIndexRoute: typeof AuthRegisterVerifyIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthRegisterSetupIndexRoute: AuthRegisterSetupIndexRoute,
  AuthRegisterVerifyIndexRoute: AuthRegisterVerifyIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface CommitteeRouteRouteChildren {
  CommitteeIndexRoute: typeof CommitteeIndexRoute
  CommitteeFormsIndexRoute: typeof CommitteeFormsIndexRoute
  CommitteeMembersIndexRoute: typeof CommitteeMembersIndexRoute
  CommitteeNoticeIndexRoute: typeof CommitteeNoticeIndexRoute
  CommitteeNoticeNoticeIdIndexRoute: typeof CommitteeNoticeNoticeIdIndexRoute
}

const CommitteeRouteRouteChildren: CommitteeRouteRouteChildren = {
  CommitteeIndexRoute: CommitteeIndexRoute,
  CommitteeFormsIndexRoute: CommitteeFormsIndexRoute,
  CommitteeMembersIndexRoute: CommitteeMembersIndexRoute,
  CommitteeNoticeIndexRoute: CommitteeNoticeIndexRoute,
  CommitteeNoticeNoticeIdIndexRoute: CommitteeNoticeNoticeIdIndexRoute,
}

const CommitteeRouteRouteWithChildren = CommitteeRouteRoute._addFileChildren(
  CommitteeRouteRouteChildren,
)

interface DevRouteRouteChildren {
  DevCommitteeMemberIndexRoute: typeof DevCommitteeMemberIndexRoute
  DevPushNotificationIndexRoute: typeof DevPushNotificationIndexRoute
  DevSearchIndexRoute: typeof DevSearchIndexRoute
  DevTableIndexRoute: typeof DevTableIndexRoute
  DevUiComponentsIndexRoute: typeof DevUiComponentsIndexRoute
}

const DevRouteRouteChildren: DevRouteRouteChildren = {
  DevCommitteeMemberIndexRoute: DevCommitteeMemberIndexRoute,
  DevPushNotificationIndexRoute: DevPushNotificationIndexRoute,
  DevSearchIndexRoute: DevSearchIndexRoute,
  DevTableIndexRoute: DevTableIndexRoute,
  DevUiComponentsIndexRoute: DevUiComponentsIndexRoute,
}

const DevRouteRouteWithChildren = DevRouteRoute._addFileChildren(
  DevRouteRouteChildren,
)

interface DocsRouteRouteChildren {
  DocsSlugRoute: typeof DocsSlugRoute
  DocsIndexRoute: typeof DocsIndexRoute
}

const DocsRouteRouteChildren: DocsRouteRouteChildren = {
  DocsSlugRoute: DocsSlugRoute,
  DocsIndexRoute: DocsIndexRoute,
}

const DocsRouteRouteWithChildren = DocsRouteRoute._addFileChildren(
  DocsRouteRouteChildren,
)

interface ProjectRouteRouteChildren {
  ProjectIndexRoute: typeof ProjectIndexRoute
  ProjectFormsIndexRoute: typeof ProjectFormsIndexRoute
  ProjectMembersIndexRoute: typeof ProjectMembersIndexRoute
  ProjectNoticeIndexRoute: typeof ProjectNoticeIndexRoute
}

const ProjectRouteRouteChildren: ProjectRouteRouteChildren = {
  ProjectIndexRoute: ProjectIndexRoute,
  ProjectFormsIndexRoute: ProjectFormsIndexRoute,
  ProjectMembersIndexRoute: ProjectMembersIndexRoute,
  ProjectNoticeIndexRoute: ProjectNoticeIndexRoute,
}

const ProjectRouteRouteWithChildren = ProjectRouteRoute._addFileChildren(
  ProjectRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  CommitteeRouteRoute: CommitteeRouteRouteWithChildren,
  DevRouteRoute: DevRouteRouteWithChildren,
  DocsRouteRoute: DocsRouteRouteWithChildren,
  ProjectRouteRoute: ProjectRouteRouteWithChildren,
  ForbiddenIndexRoute: ForbiddenIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
